language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-add-repository ppa:beineri/opt-qt-5.12.6-xenial -y;
      sudo apt-get update -q;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install qt512base qt512tools qt512quickcontrols qt512quickcontrols2 qt512graphicaleffects qt512svg qt512imageformats qt512charts-no-lgpl qt512location -y;
      sudo apt-get install libgl1-mesa-dev -y;
      sudo apt-get install libtool automake m4 -y;
    fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt512/bin/qt512-env.sh; fi
  - cd contribs/; python3 contribs.py; cd ..;
  - qmake --version
  - qmake DEFINES+=USE_CONTRIBS CONFIG+=release PREFIX=/usr

script:
  - make -j$(nproc)
