language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-add-repository ppa:beineri/opt-qt-5.14.1-xenial -y;
      sudo apt-get update -q;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install qt514base qt514tools qt514quickcontrols qt514quickcontrols2 qt514graphicaleffects qt514svg qt514imageformats qt514charts-no-lgpl qt514location -y;
      sudo apt-get install libgl1-mesa-dev -y;
      sudo apt-get install ninja libtool automake m4 -y;
    fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt514/bin/qt514-env.sh; fi
  - cd contribs/; python3 contribs.py; cd ..;
  - qmake --version
  - qmake DEFINES+=USE_CONTRIBS CONFIG+=release PREFIX=/usr

script:
  - make -j$(nproc)
