#--------------------------------------------------------------------------------
# Workflow configuration
#--------------------------------------------------------------------------------

name: "CI builds"
on:
  push:
  pull_request:

#--------------------------------------------------------------------------------
# Define application name & version
#--------------------------------------------------------------------------------

env:
  QMAKE_PROJECT: "MiniVideoInfos.pro"
  APPLICATION: "MiniVideoInfos"
  VERSION: "0.10"

#--------------------------------------------------------------------------------
# Workflow jobs
#--------------------------------------------------------------------------------

jobs:
  ## GNU/Linux build ###########################################################
  build-linux:
    name: "Linux CI build"
    runs-on: ubuntu-20.04
    steps:
      # Checkout the repository
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          aqtversion: '==2.1.0'
          version: '6.3.1'
          modules: qt5compat qtimageformats qtpositioning qtcharts qtshadertools
          cached: 'false'

      # Install dependencies (from package manager)
      - name: Install dependencies (from package manager)
        run: |
             sudo apt-get install libgl1-mesa-dev -y;
             sudo apt-get install cmake ninja-build libtool automake m4 -y;
             sudo apt-get install appstream -y;

      # Build dependencies (from contribs script)
      - name: Build dependencies (from contribs script)
        run: |
             cd contribs/
             python3 contribs.py --qt-directory ${{env.Qt6_DIR}}/../.. --targets=linux
             cd ..

      # Build application
      - name: Build application
        run: |
             qmake ${{env.QMAKE_PROJECT}} DEFINES+=USE_CONTRIBS CONFIG+=release PREFIX=/usr
             make -j$(nproc)
